// main.idl: main 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(main.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	uuid(f17db82d-29b8-4245-9ea9-6182eea7bd33),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{7e9a7989-5402-4cff-a8b8-cf769972d901}")
]
library mainLib
{
	importlib("stdole2.tlb");
	[
		uuid(7e9a7989-5402-4cff-a8b8-cf769972d901)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
};

import "shobjidl.idl";
import "shobjidl.idl";
